@startuml
' Use Case Diagram for ATM System

actor Customer
actor Bank

ATM as atm

Customer -- (Withdraw Cash)
Customer -- (Check Balance)
Customer -- (Deposit Cash)
Customer -- (Print Receipt)

(Withdraw Cash) -- (Print Receipt)
(Deposit Cash) -- (Print Receipt)

Bank -- (Maintain ATM)

@enduml
